#!/bin/sh
BLKDEV=/dev/mmcblk0
ROOTPART_SEQ=3

dialog --title Testing --infobox "Initing System, Please Wait A Moment....." 20 60

parted -s $BLKDEV -- resizepart $ROOTPART_SEQ 100%

resize.f2fs /dev/mmcblk0p3 >> /dev/null

cd /boot

rm bcm2708-rpi-b.dtb >> /dev/null
rm bcm2708-rpi-b-plus.dtb >> /dev/null
rm bcm2708-rpi-cm.dtb >> /dev/null
rm bcm2708-rpi-zero.dtb >> /dev/null
rm bcm2708-rpi-zero-w.dtb >> /dev/null
rm bcm2709-rpi-2-b.dtb >> /dev/null
rm BUILD-DATA >> /dev/null
rm -rf defaults >> /dev/null
rm -rf overlays >> /dev/null
rm recover4.elf >> /dev/null
rm recovery7.img >> /dev/null
rm recovery7l.img >> /dev/null
rm recovery.cmdline >> /dev/null
rm recovery.elf >> /dev/null
rm RECOVERY_FILES_DO_NOT_EDIT >> /dev/null
rm recovery.img >> /dev/null
rm recovery.rfs >> /dev/null
rm riscos-boot.bin >> /dev/null

mv EFI-BOOT/* . >> /dev/null
rmdir EFI-BOOT >> /dev/null

sync

sleep 5
reboot
